/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
};
typedef struct numbers numbers;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(numbers *, CLIENT *);
extern  int * soma_1_svc(numbers *, struct svc_req *);
#define resto 2
extern  int * resto_1(numbers *, CLIENT *);
extern  int * resto_1_svc(numbers *, struct svc_req *);
#define divisao 3
extern  int * divisao_1(numbers *, CLIENT *);
extern  int * divisao_1_svc(numbers *, struct svc_req *);
#define multiplicacao 4
extern  int * multiplicacao_1(numbers *, CLIENT *);
extern  int * multiplicacao_1_svc(numbers *, struct svc_req *);
#define sair 5
extern  int * sair_1(numbers *, CLIENT *);
extern  int * sair_1_svc(numbers *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define resto 2
extern  int * resto_1();
extern  int * resto_1_svc();
#define divisao 3
extern  int * divisao_1();
extern  int * divisao_1_svc();
#define multiplicacao 4
extern  int * multiplicacao_1();
extern  int * multiplicacao_1_svc();
#define sair 5
extern  int * sair_1();
extern  int * sair_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
