/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host, int o, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  soma_1_arg;
	int  *result_2;
	numbers  resto_1_arg;
	int  *result_3;
	numbers  divisao_1_arg;
	int  *result_4;
	numbers  multiplicacao_1_arg;
	int  *result_5;
	numbers  sair_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

do{
	printf("\n");
	printf("-------------Calculadora-------------\n");
	printf("\n");
	printf("----Qual operação deseja realizar?---\n");
	printf("\n");
	printf("1.- Soma\n2.- Subtração \n3.- Divisão \n4.- Multiplicação \n5.- Sair \n  ");
	printf("\n");
	scanf("%d", &o);
	printf("\n");
	printf("----Informe o primeiro número: \n");
	scanf("%d", &a);
	printf("----Informe o segundo número: \n");
	scanf("%d", &b);
	printf("\n");
	switch(o){

		case 1:
			soma_1_arg.a=a;
			soma_1_arg.b=b;
			result_1 = soma_1(&soma_1_arg, clnt);
			if (result_1 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("-->Soma: %d \n", *result_1);
			break;
		case 2:
			resto_1_arg.a=a;
			resto_1_arg.b=b;
			result_2 = resto_1(&resto_1_arg, clnt);
			if (result_2 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("-->Subtração: %d \n", *result_2);
			break;
		case 3:
			divisao_1_arg.a=a;
			divisao_1_arg.b=b;
			result_3 = divisao_1(&divisao_1_arg, clnt);
			if (result_3 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("-->Divisão inteira: %d \n", *result_3);
			break;
		case 4:
			multiplicacao_1_arg.a=a;
			multiplicacao_1_arg.b=b;
			result_4 = multiplicacao_1(&multiplicacao_1_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("-->Multiplicação: %d \n", *result_4);
			break;
		case 5:
			result_5 = sair_1(&sair_1_arg, clnt);
			if (result_5 == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

while(o != 5);

}

int
main (int argc, char *argv[])
{
	char *host;
	int o;
	int a;
	int b;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host, o, a, b);
exit (0);
}

