/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
soma_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;


	printf("soma(%d, %d)is called\n)", argp->a,argp->b);
	result = argp->a + argp->b;
	return &result;
}

int *
resto_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("resto(%d, %d) is called\n", argp->a, argp->b);	 
	result = argp-> a - argp->b;
	return &result;
}

int *
divisao_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("divisao(%d, %d) is called\n", argp->a, argp->b);
	result = argp-> a / argp->b;

	return &result;
}

int *
multiplicacao_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("multiplicacao(%d, %d) is called", argp->a, argp->b);
	result = argp->a * argp->b;
}

int *
sair_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
